import PROVINCE from './province.js'
import { UPLOAD_FILE } from '@/api'
import moment from 'moment'
export const formConf = {
  formRef: 'elForm',
  formModel: 'formData',
  size: 'small',
  labelPosition: 'right',
  labelWidth: 100,
  formRules: 'rules',
  gutter: 15,
  disabled: false,
  span: 24,
  formBtns: true
}
// 基础组件
export const inputComponents = [
  {
    label: '单行输入框',
    tag: 'el-input',
    tagIcon: 'input',
    placeholder: '请输入',
    defaultValue: undefined,
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    clearable: true,
    prepend: '',
    append: '',
    'prefix-icon': '',
    'suffix-icon': '',
    maxlength: null,
    'show-word-limit': false,
    readonly: false,
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false,
    asSummary: false
  },
  {
    label: '多行输入框',
    tag: 'el-input',
    tagIcon: 'textarea',
    type: 'textarea',
    placeholder: '请输入',
    defaultValue: undefined,
    span: 24,
    labelWidth: null,
    autosize: {
      minRows: 4,
      maxRows: 4
    },
    style: { width: '100%' },
    maxlength: null,
    'show-word-limit': false,
    readonly: false,
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false,
    asSummary: false
  },
  {
    label: '密码',
    tag: 'el-input',
    tagIcon: 'password',
    placeholder: '请输入',
    defaultValue: undefined,
    span: 24,
    'show-password': true,
    labelWidth: null,
    style: { width: '100%' },
    clearable: true,
    prepend: '',
    append: '',
    'prefix-icon': '',
    'suffix-icon': '',
    maxlength: null,
    'show-word-limit': false,
    readonly: false,
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false,
    asSummary: false
  },
  {
    label: '数字输入框',
    tag: 'el-input-number',
    tagIcon: 'number',
    placeholder: '',
    defaultValue: undefined,
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: true
  },
  {
    label: '金额',
    tag: 'fc-amount',
    tagIcon: 'amount',
    placeholder: '请输入',
    defaultValue: undefined,
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: true,
    showChinese: true
  }
]
//选择组件
export const selectComponents = [
  {
    label: '下拉选择',
    tag: 'el-select',
    tagIcon: 'select',
    placeholder: '请选择',
    style: { width: '100%' },
    defaultValue: undefined,
    span: 24,
    labelWidth: null,
    clearable: true,
    disabled: false,
    required: false,
    filterable: false,
    proCondition: true,
    multiple: false,
    options: [
      {
        label: '选项一',
        value: '选项一'
      },
      {
        label: '选项二',
        value: '选项二'
      }
    ],
    regList: [],
    changeTag: true
  },
  {
    label: '级联选择',
    tag: 'el-cascader',
    tagIcon: 'cascader',
    placeholder: '请选择',
    defaultValue: [],
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    props: {
      props: {
        multiple: false
      }
    },
    'show-all-levels': true,
    disabled: false,
    clearable: true,
    filterable: false,
    required: false,
    options: [
      {
        id: 1,
        value: '选项1',
        label: '选项1',
        children: [
          {
            id: 2,
            value: '选项1-1',
            label: '选项1-1'
          }
        ]
      }
    ],
    dataType: 'static',
    labelKey: 'label',
    valueKey: 'value',
    childrenKey: 'children',
    separator: '/',
    regList: [],
    changeTag: true,
    proCondition: false,
    asSummary: false
  },
  {
    label: '省市区',
    tag: 'el-cascader',
    tagIcon: 'area',
    placeholder: '请选择',
    defaultValue: [],
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    props: {
      props: {
        multiple: false
      }
    },
    'show-all-levels': true,
    disabled: false,
    clearable: true,
    filterable: false,
    required: false,
    options: PROVINCE,
    dataType: 'static',
    labelKey: 'label',
    valueKey: 'value',
    childrenKey: 'children',
    separator: '/',
    regList: [],
    changeTag: true,
    proCondition: false,
    asSummary: false
  },
  {
    label: '单选框组',
    tag: 'el-radio-group',
    tagIcon: 'radio',
    defaultValue: undefined,
    span: 24,
    labelWidth: null,
    style: {},
    optionType: 'default',
    border: false,
    size: 'medium',
    disabled: false,
    required: false,
    options: [
      {
        label: '选项一',
        value: '选项一'
      },
      {
        label: '选项二',
        value: '选项二'
      }
    ],
    regList: [],
    changeTag: true,
    proCondition: true
  },
  {
    label: '多选框组',
    tag: 'el-checkbox-group',
    tagIcon: 'checkbox',
    defaultValue: [],
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    optionType: 'default',
    border: false,
    size: 'medium',
    disabled: false,
    required: false,
    options: [
      {
        label: '选项一',
        value: '选项一'
      },
      {
        label: '选项二',
        value: '选项二'
      }
    ],
    regList: [],
    changeTag: true,
    proCondition: false,
    asSummary: false
  },
  //   {
  //     label: '开关',
  //     tag: 'el-switch',
  //     tagIcon: 'switch',
  //     defaultValue: false,
  //     span: 24,
  //     labelWidth: null,
  //     style: {},
  //     disabled: false,
  //     required: false,
  //     'active-text': '',
  //     'inactive-text': '',
  //     'active-color': null,
  //     'inactive-color': null,
  //     'active-value': true,
  //     'inactive-value': false,
  //     regList: [],
  //     changeTag: true,
  // proCondition: false,
  // asSummary: false
  //   },
  {
    label: '滑块',
    tag: 'el-slider',
    tagIcon: 'slider',
    defaultValue: null,
    span: 24,
    labelWidth: null,
    disabled: false,
    required: false,
    style: { width: '100%' },
    min: 0,
    max: 100,
    step: 1,
    'show-stops': false,
    range: false,
    regList: [],
    changeTag: true,
    proCondition: false,
    asSummary: false
  },
  // {
  //   label: '组织机构',
  //   tag: 'fc-org-selectnew',
  //   tagIcon: 'dept',
  //   defaultValue: null,
  //   accept: 'employee,position,role',
  //   title: '组织机构',
  //   searchable: true,
  //   maxNum: 1,
  //   tagConfig: {
  //     type: 'info',
  //     closable: true,
  //     'disable-transitions': false,
  //     hit: false,
  //     color: undefined,
  //     size: 'small',
  //     effect: 'light'
  //   },
  //   style: { width: '100%' },
  //   span: 24,
  //   labelWidth: null,
  //   disabled: false,
  //   required: true,
  //   regList: [],
  //   changeTag: true,
  //   proCondition: true,
  //   asSummary: false
  // },
  /*{
  label: '组织机构',
  tag: 'fc-org-select',
  tagIcon: 'dept',
  defaultValue: null,
  tabList: ['dep'],
  buttonType: 'button',
  title: '组织机构',
  searchable: true,
  maxNum: 1,
  tagConfig: {
    type: 'info',
    closable: true,
    'disable-transitions': false,
    hit: false,
    color: undefined,
    size: 'small',
    effect: 'light'
  },
  style: { width: '100%' },
  span: 24,
  labelWidth: null,
  disabled: false,
  required: true,
  regList: [],
  changeTag: true,
  proCondition: true,
  asSummary: false
},*/

  {
    label: '时间选择',
    tag: 'el-time-picker',
    tagIcon: 'time',
    placeholder: '请选择',
    defaultValue: null,
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    disabled: false,
    clearable: true,
    required: false,
    'picker-options': {
      selectableRange: '00:00:00-23:59:59'
    },
    showDuration: true,
    format: 'HH:mm:ss',
    'value-format': 'HH:mm:ss',
    regList: [],
    changeTag: true,
    proCondition: false,
    asSummary: false
  },
  {
    label: '时间范围',
    tag: 'fc-time-duration',
    showDuration: true,
    tagIcon: 'time-range',
    defaultValue: null,
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    disabled: false,
    clearable: true,
    required: false,
    'is-range': true,
    'range-separator': '至',
    'start-placeholder': '开始时间',
    'end-placeholder': '结束时间',
    format: 'HH:mm:ss',
    'value-format': 'HH:mm:ss',
    regList: [],
    changeTag: true,
    proCondition: true,
    asSummary: false
  },
  {
    label: '日期选择',
    tag: 'el-date-picker',
    tagIcon: 'date',
    placeholder: '请选择',
    defaultValue: moment(new Date()).format('YYYY-MM-DD'),
    type: 'date',
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    disabled: false,
    clearable: true,
    required: false,
    format: 'yyyy-MM-dd',
    'value-format': 'yyyy-MM-dd',
    readonly: false,
    regList: [],
    changeTag: true,
    proCondition: false,
    asSummary: false
  },
  {
    label: '日期范围',
    tag: 'fc-date-duration',
    showDuration: false,
    tagIcon: 'date-range',
    defaultValue: null,
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    type: 'daterange',
    'range-separator': '至',
    'start-placeholder': '开始日期',
    'end-placeholder': '结束日期',
    disabled: false,
    clearable: true,
    required: false,
    format: 'yyyy-MM-dd',
    'value-format': 'yyyy-MM-dd',
    readonly: false,
    regList: [],
    changeTag: true,
    proCondition: true,
    asSummary: false
  },
  {
    label: '评分',
    tag: 'el-rate',
    tagIcon: 'rate',
    defaultValue: 0,
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    max: 5,
    'allow-half': false,
    'show-text': false,
    'show-score': false,
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false,
    asSummary: false
  }
  //   {
  //     label: '颜色选择',
  //     tag: 'el-color-picker',
  //     tagIcon: 'color',
  //     defaultValue: null,
  //     labelWidth: null,
  //     'show-alpha': false,
  //     'color-format': '',
  //     disabled: false,
  //     required: false,
  //     size: 'medium',
  //     regList: [],
  //     changeTag: true,
  // proCondition: false,
  // asSummary: false
  //   },
]
// 容器组件
export const layoutComponents = [
  {
    layout: 'rowFormItem',
    rowType: 'layout',
    tagIcon: 'row',
    type: 'default',
    justify: 'start',
    align: 'top',
    label: '布局容器',
    layoutTree: true,
    children: [],
    showDivider: true
  },
  {
    layout: 'rowFormItem',
    rowType: 'table',
    tagIcon: 'table',
    tag: 'fc-input-table',
    type: 'table', // list
    justify: 'start',
    align: 'top',
    label: '表格/明细',
    layoutTree: false,
    children: [],
    actionText: '添加',
    tableConf: {},
    'show-summary': true,
    defaultValue: []
  }
]
// 自定义组件
export const returnPremines = [
  {
    label: '月份选择',
    tag: 'fc-date-select',
    tagIcon: 'date',
    placeholder: '请选择',
    defaultValue:'',
    type: 'date',
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    disabledMonth:'',
    disabled: false,
    clearable: true,
    required: false,
    format: 'yyyy-MM',
    'value-format': 'yyyy-MM',
    readonly: false,
    regList: [],
    changeTag: true,
    proCondition: false,
    asSummary: false
  },
  {
    label: '远程下拉选择',
    type: 'apiSelect',
    tagType: 'conponent',
    tag: 'fc-api-select',
    placeholder: '请选择',
    defaultValue: undefined,
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    readonly: false,
    required: false,
    bindPrice: '',
    bindPriceKey: '',
    source: 'erp',
    url: '',
    method: 'get',
    optionKey: 'id',
    optionValue: 'name'
  },
  {
    label: '计算公式',
    type: 'calculate',
    tag: 'fc-calculate',
    showChinese: true,
    tagIcon: 'calculate',
    tagType: 'conponent',
    defaultValue: null,
    style: { width: '100%' },
    labelWidth: null,
    disabled: false,
    required: false,
    span: 24,
    changeTag: true,
    expression: [],
    proCondition: true,
    asSummary: false
  },
  // {
  //   label: '条件公式',
  //   type: 'condition',
  //   tag: 'fc-condition',
  //   tagIcon: 'condition',
  //   style: { width: '100%' },
  //   tagType: 'conponent',
  //   defaultValue: null,
  //   labelWidth: null,
  //   span: 24,
  //   disabled: false,
  //   required: true,
  //   readonly: false,
  //   changeTag: true,
  //   condition: [],
  //   conValue: '',
  //   proCondition: false,
  //   asSummary: false
  // },
  {
    label: '发票金额',
    type: 'totalMoney',
    tag: 'fc-total-money',
    // tagIcon: 'number',
    bindPrice: '',
    style: { width: '100%' },
    tagType: 'conponent',
    placeholder: '',
    defaultValue: 0,
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    showChinese: false,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: true
  },
  {
    label: '附件数量',
    tag: 'fc-upload-quantity',
    tagIcon: 'uploadQuantity',
    bindPrice: '',
    placeholder: '请输入',
    defaultValue: undefined,
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: true
  },
  {
    label: '上传附件',
    type: 'uploadFile',
    tag: 'fc-uploadFile',
    tagType: 'conponent',
    defaultValue: undefined,
    uploadFileType: 'default',
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false
  },
  {
    label: '选择学校',
    type: 'selectSchool',
    tagType: 'conponent',
    tag: 'fc-select-school',
    defaultValue: undefined,
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false
  },
  {
    label: '费用名称',
    type: 'selectFeeName',
    tagType: 'conponent',
    tag: 'fc-select-feeName',
    defaultValue: undefined,
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: true
  },
  {
    label: '单位',
    type: 'selectUnit',
    tagType: 'conponent',
    bindPrice: '',
    tag: 'fc-select-unit',
    defaultValue: undefined,
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false
  },
  {
    label: '拆分',
    type: 'selectFeeType',
    tagType: 'conponent',
    tag: 'fc-select-feeType',
    bindTypePrice: '',
    defaultValue: undefined,
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false
  },
  {
    label: '付款分馆',
    type: 'selectFinance',
    tagType: 'conponent',
    tag: 'fc-select-finance',
    defaultValue: undefined,
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false
  },
  {
    label: '分摊',
    type: 'apportion',
    tagType: 'conponent',
    tag: 'fc-apportion',
    bindPrice: '',
    defaultValue: undefined,
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false
  },
  {
    label: '成本归类',
    type: 'selectCostType',
    tagType: 'conponent',
    approveType: '报销单',
    bindPrice: '',
    bindTypePrice: '',
    defaultType: 'feeItemName',
    tag: 'fc-select-costType',
    defaultValue: undefined,
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false
  },
  {
    label: '选择银行',
    type: 'selectBank',
    tag: 'fc-select-bank',
    defaultValue: undefined,
    style: { width: null },
    defaultType: 'default',
    span: 24,
    tagType: 'conponent',
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false
  },
  {
    label: '收款银行',
    type: 'selectBankList',
    tagType: 'conponent',
    tag: 'fc-select-bankList',
    defaultValue: undefined,
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false
  },
  {
    label: '员工',
    type: 'selectEmployee',
    tag: 'fc-select-employee',
    placeholder: '请选择',
    defaultValue: undefined,
    defaultType: 'default',
    style: { width: null },
    span: 24,
    labelWidth: null,
    tagType: 'conponent',
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false
  },
  {
    label: '选择分馆',
    type: 'selectBranch',
    tagType: 'conponent',
    tag: 'fc-select-branch',
    defaultType: 'default',
    defaultBranch: false,
    defaultValue: undefined,
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false
  },
  {
    label: '下拉选择银行',
    type: 'filterBank',
    tagType: 'conponent',
    tag: 'fc-filter-bank',
    defaultValue: undefined,
    bindPrice: '',
    defaultType: 'default',
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    regList: [],
    changeTag: true,
    proCondition: false
  },
  {
    label: '输入验证',
    type: 'inputVerify',
    tagType: 'conponent',
    tag: 'fc-input-verify',
    placeholder: '请输入',
    defaultValue: undefined,
    defaultType: 'button',
    url: '',
    method: 'get',
    paramsKey: '',
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    readonly: false,
    required: false
  },
  {
    label: '业绩',
    type: 'perList',
    tagType: 'conponent',
    tag: 'fc-per-list',
    defaultType: 'adviser',
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    disabled: false,
    readonly: false,
    required: false
  },
  {
    label: '资源来源',
    type: 'source',
    tagType: 'conponent',
    tag: 'fc-source',
    placeholder: '请输入',
    defaultValue: undefined,
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    readonly: false,
    required: false
  },
  {
    label: '投票',
    tag: 'fc-vote',
    type: 'vote',
    tagType: 'conponent',
    span: 24,
    labelWidth: null,
    style: { width: '100%' },
    border: false,
    disabled: false,
    required: false,
    defaultType: 'radio',
    options: [
      {
        label: '选项一',
        value: '选项一',
        describe: ''
      },
      {
        label: '选项二',
        value: '选项二',
        describe: ''
      }
    ]
  }
  // {
  //   label: '支付方式类型',
  //   type: 'selectPayType',
  //   tagType: 'conponent',
  //   tag: 'fc-select-payType',
  //   defaultValue: undefined,
  //   style: { width: null },
  //   span: 24,
  //   labelWidth: null,
  //   min: undefined,
  //   max: undefined,
  //   step: undefined,
  //   'step-strictly': false,
  //   precision: undefined,
  //   'controls-position': 'left',
  //   disabled: false,
  //   required: false,
  //   regList: [],
  //   changeTag: true,
  //   proCondition: false,
  //   showChinese: true
  // }
  // {
  //   layout: 'rowFormItem',
  //   rowType: 'table',
  //   tagIcon: 'table',
  //   tag: 'fc-input-student',
  //   type: 'list', // list
  //   justify: 'start',
  //   align: 'top',
  //   label: '定制容器',
  //   layoutTree: false,
  //   children: [],
  //   actionText: '',
  //   tableConf: {},
  //   'show-summary': true,
  //   defaultValue: []
  // }
]
export const commonComponents = [...inputComponents, ...selectComponents, ...layoutComponents].map(t => Object.assign({ cmpType: 'common' }, t))

const getConfigByTag = (targetList, tag) => targetList.find(t => t.tag === tag)
const copyConfigAsCustom = (rowConf, childrenConf) => {
  const clone = (target, conf = {}) => {
    const template = JSON.parse(JSON.stringify(target))
    return Object.assign({}, template, { cmpType: 'custom' }, conf)
  }
  const defaultRow = clone(layoutComponents[0], rowConf)
  defaultRow.children = childrenConf.map(t => clone(t.target, t.config))
  return defaultRow
}
const chooseStudent = [
  {
    label: '选择学员',
    type: 'selectStudent',
    tag: 'fc-return-student',
    tagType: 'conponent',
    defaultValue: [],
    style: { width: null },
    span: 24,
    labelWidth: null,
    min: undefined,
    max: undefined,
    step: undefined,
    'step-strictly': false,
    precision: undefined,
    'controls-position': 'left',
    disabled: false,
    required: false,
    changeTag: true,
    proCondition: false
  }
]
// 定制组件添加cmpType = custom
export const customMadeComponents = [
  // {
  //   layout: 'rowFormItem',
  //   rowType: 'table',
  //   tagIcon: 'table',
  //   tag: 'fc-input-student',
  //   type: 'list', // list
  //   justify: 'start',
  //   align: 'top',
  //   label: '学员组件',
  //   layoutTree: false,
  //   vModel: 'MemberCourseInfo',
  //   children: [
  //     Object.assign(getConfigByTag(chooseStudent, 'fc-return-student'), {
  //       required: true,
  //       label: '选择学员',
  //       showDuration: true,
  //       vModel: 'memberInfo'
  //     }),
  //     {
  //       label: '学员姓名',
  //       tag: 'el-input',
  //       tagIcon: 'input',
  //       placeholder: '请输入',
  //       defaultValue: undefined,
  //       span: 12,
  //       labelWidth: null,
  //       style: { width: '100%' },
  //       clearable: true,
  //       prepend: '',
  //       append: '',
  //       'prefix-icon': '',
  //       'suffix-icon': '',
  //       maxlength: null,
  //       'show-word-limit': false,
  //       readonly: true,
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       changeTag: true,
  //       proCondition: false,
  //       asSummary: false,
  //       vModel: 'member_memberName'
  //     },
  //     {
  //       label: '联系方式',
  //       tag: 'el-input',
  //       tagIcon: 'input',
  //       placeholder: '请输入',
  //       defaultValue: undefined,
  //       span: 12,
  //       labelWidth: null,
  //       style: { width: '100%' },
  //       clearable: true,
  //       prepend: '',
  //       append: '',
  //       'prefix-icon': '',
  //       'suffix-icon': '',
  //       maxlength: null,
  //       'show-word-limit': false,
  //       readonly: true,
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       changeTag: true,
  //       proCondition: false,
  //       asSummary: false,
  //       vModel: 'member_memberPhone'
  //     },
  //     {
  //       label: '学员卡号',
  //       tag: 'el-input',
  //       tagIcon: 'input',
  //       placeholder: '请输入',
  //       defaultValue: undefined,
  //       span: 12,
  //       labelWidth: null,
  //       style: { width: '100%' },
  //       clearable: true,
  //       prepend: '',
  //       append: '',
  //       'prefix-icon': '',
  //       'suffix-icon': '',
  //       maxlength: null,
  //       'show-word-limit': false,
  //       readonly: true,
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       changeTag: true,
  //       proCondition: false,
  //       asSummary: false,
  //       vModel: 'memberCourse_cardNo'
  //     },
  //     {
  //       label: '卡种名称',
  //       tag: 'el-input',
  //       tagIcon: 'input',
  //       placeholder: '请输入',
  //       defaultValue: undefined,
  //       span: 12,
  //       labelWidth: null,
  //       style: { width: '100%' },
  //       clearable: true,
  //       prepend: '',
  //       append: '',
  //       'prefix-icon': '',
  //       'suffix-icon': '',
  //       maxlength: null,
  //       'show-word-limit': false,
  //       readonly: true,
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       changeTag: true,
  //       proCondition: false,
  //       asSummary: false,
  //       vModel: 'memberCourse_courseName'
  //     },
  //     {
  //       label: '总缴费金额',
  //       tag: 'el-input-number',
  //       tagIcon: 'number',
  //       placeholder: '',
  //       defaultValue: undefined,
  //       style: { width: '100%' },
  //       span: 12,
  //       labelWidth: null,
  //       min: undefined,
  //       max: undefined,
  //       step: undefined,
  //       'step-strictly': false,
  //       precision: undefined,
  //       'controls-position': 'left',
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       changeTag: true,
  //       proCondition: true,
  //       vModel: 'memberCourse_receivedPrice'
  //     },
  //     {
  //       label: '总次数',
  //       tag: 'el-input-number',
  //       tagIcon: 'number',
  //       placeholder: '',
  //       defaultValue: undefined,
  //       style: { width: '100%' },
  //       span: 12,
  //       labelWidth: null,
  //       min: undefined,
  //       max: undefined,
  //       step: undefined,
  //       'step-strictly': false,
  //       precision: undefined,
  //       'controls-position': 'left',
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       changeTag: true,
  //       proCondition: true,
  //       vModel: 'memberCourse_num'
  //     },
  //     {
  //       label: '使用次数',
  //       tag: 'el-input-number',
  //       tagIcon: 'number',
  //       placeholder: '',
  //       defaultValue: undefined,
  //       style: { width: '100%' },
  //       span: 12,
  //       labelWidth: null,
  //       min: undefined,
  //       max: undefined,
  //       step: undefined,
  //       'step-strictly': false,
  //       precision: undefined,
  //       'controls-position': 'left',
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       changeTag: true,
  //       proCondition: true,
  //       vModel: 'memberCourse_used'
  //     },
  //     {
  //       label: '缴费日期',
  //       tag: 'el-input-number',
  //       tagIcon: 'number',
  //       placeholder: '',
  //       defaultValue: undefined,
  //       style: { width: '100%' },
  //       span: 12,
  //       labelWidth: null,
  //       min: undefined,
  //       max: undefined,
  //       step: undefined,
  //       'step-strictly': false,
  //       precision: undefined,
  //       'controls-position': 'left',
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       changeTag: true,
  //       proCondition: true,
  //       vModel: 'memberCourse_buyDate'
  //     },
  //     {
  //       label: '学籍管理费默认',
  //       tag: 'el-input-number',
  //       tagIcon: 'number',
  //       placeholder: '',
  //       defaultValue: undefined,
  //       style: { width: '100%' },
  //       span: 12,
  //       labelWidth: null,
  //       min: undefined,
  //       max: undefined,
  //       step: undefined,
  //       'step-strictly': false,
  //       precision: undefined,
  //       'controls-position': 'left',
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       changeTag: true,
  //       proCondition: true,
  //       vModel: 'memberCourse_defaultPrice'
  //     },
  //     {
  //       label: '扣除课耗',
  //       tag: 'el-input-number',
  //       tagIcon: 'number',
  //       placeholder: '',
  //       defaultValue: undefined,
  //       style: { width: '100%' },
  //       span: 12,
  //       labelWidth: null,
  //       min: undefined,
  //       max: undefined,
  //       step: undefined,
  //       'step-strictly': false,
  //       precision: undefined,
  //       'controls-position': 'left',
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       changeTag: true,
  //       proCondition: true,
  //       vModel: 'memberCourse_classConsumpPrice'
  //     },
  //     {
  //       label: '舞种',
  //       tag: 'el-input-number',
  //       tagIcon: 'number',
  //       placeholder: '',
  //       defaultValue: undefined,
  //       style: { width: '100%' },
  //       span: 12,
  //       labelWidth: null,
  //       min: undefined,
  //       max: undefined,
  //       step: undefined,
  //       'step-strictly': false,
  //       precision: undefined,
  //       'controls-position': 'left',
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       changeTag: true,
  //       proCondition: true,
  //       vModel: 'memberCourse_dance'
  //     },
  //     {
  //       label: '班型',
  //       tag: 'el-input-number',
  //       tagIcon: 'number',
  //       placeholder: '',
  //       defaultValue: undefined,
  //       style: { width: '100%' },
  //       span: 12,
  //       labelWidth: null,
  //       min: undefined,
  //       max: undefined,
  //       step: undefined,
  //       'step-strictly': false,
  //       precision: undefined,
  //       'controls-position': 'left',
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       changeTag: true,
  //       proCondition: true,
  //       vModel: 'memberCourse_category'
  //     },
  //     {
  //       label: '上课分馆',
  //       tag: 'el-input-number',
  //       tagIcon: 'number',
  //       placeholder: '',
  //       defaultValue: undefined,
  //       style: { width: '100%' },
  //       span: 12,
  //       labelWidth: null,
  //       min: undefined,
  //       max: undefined,
  //       step: undefined,
  //       'step-strictly': false,
  //       precision: undefined,
  //       'controls-position': 'left',
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       changeTag: true,
  //       proCondition: true,
  //       vModel: 'memberCourse_classBranchName'
  //     },
  //     {
  //       label: '办卡分馆',
  //       tag: 'el-input-number',
  //       tagIcon: 'number',
  //       placeholder: '',
  //       defaultValue: undefined,
  //       style: { width: '100%' },
  //       span: 12,
  //       labelWidth: null,
  //       min: undefined,
  //       max: undefined,
  //       step: undefined,
  //       'step-strictly': false,
  //       precision: undefined,
  //       'controls-position': 'left',
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       changeTag: true,
  //       proCondition: true,
  //       vModel: 'memberCourse_courseBranchName'
  //     },
  //     {
  //       label: '业绩信息',
  //       tag: 'el-input',
  //       tagIcon: 'input',
  //       placeholder: '',
  //       defaultValue: undefined,
  //       style: { width: '100%' },
  //       span: 24,
  //       labelWidth: null,
  //       min: undefined,
  //       max: undefined,
  //       step: undefined,
  //       'step-strictly': false,
  //       precision: undefined,
  //       'controls-position': 'left',
  //       disabled: true,
  //       required: false,
  //       regList: [],
  //       hidden: false,
  //       changeTag: true,
  //       proCondition: true,
  //       vModel: 'performanceList'
  //     }
  //   ],
  //   actionText: '',
  //   tableConf: {},
  //   'show-summary': true,
  //   defaultValue: []
  // },
  copyConfigAsCustom({ label: '请假组件', explain: null }, [
    {
      target: getConfigByTag(selectComponents, 'el-select'),
      config: {
        label: '请假类型',
        required: true,
        options: [
          {
            label: '病假',
            value: '病假'
          },
          {
            label: '事假',
            value: '事假'
          },
          {
            label: '婚假',
            value: '婚假'
          },
          {
            label: '丧假',
            value: '丧假'
          },
          {
            label: '产假',
            value: '产假'
          },
          {
            label: '年假',
            value: '年假'
          }
        ]
      }
    },
    {
      target: getConfigByTag(selectComponents, 'fc-date-duration'),
      config: {
        required: true,
        label: '日期范围',
        showDuration: true
      }
    }
  ]),
  copyConfigAsCustom({ label: '出差组件', explain: null }, [
    {
      target: getConfigByTag(inputComponents, 'el-input'),
      config: {
        label: '出差事由',
        required: true
      }
    },
    {
      target: getConfigByTag(selectComponents, 'el-select'),
      config: {
        label: '交通工具',
        required: true,
        options: [
          {
            label: '火车',
            value: '火车'
          },
          {
            label: '飞机',
            value: '飞机'
          },
          {
            label: '汽车',
            value: '汽车'
          },
          {
            label: '其他',
            value: '其他'
          }
        ]
      }
    },
    {
      target: getConfigByTag(selectComponents, 'el-select'),
      config: {
        label: '单程往返',
        required: true,
        options: [
          {
            label: '单程',
            value: '单程'
          },
          {
            label: '往返',
            value: '往返'
          }
        ]
      }
    },
    {
      target: getConfigByTag(inputComponents, 'el-input'),
      config: {
        label: '出发城市',
        required: true
      }
    },
    {
      target: getConfigByTag(inputComponents, 'el-input'),
      config: {
        label: '目的城市',
        required: true
      }
    },
    {
      target: getConfigByTag(selectComponents, 'fc-date-duration'),
      config: {
        label: '日期范围',
        tag: 'fc-date-duration',
        showDuration: true,
        required: true
      }
    },
    {
      target: getConfigByTag(inputComponents, 'el-input'),
      config: {
        label: '出差备注',
        required: false
      }
    },
    {
      target: getConfigByTag(inputComponents, 'el-input'),
      config: {
        label: '同行人',
        required: false
      }
    }
  ])
]
// .map( t => Object.assign( { cmpType: 'custom', t } ) )
// 组件rule的触发方式，无触发方式的组件不生成rule
// inputTable组件也有一份此常量的copy 如有改动 最好同步
export const trigger = {
  'el-input': 'blur',
  'fc-condition': 'blur',
  'el-input-number': 'blur',
  'el-select': 'change',
  'el-radio-group': 'change',
  'el-checkbox-group': 'change',
  'el-cascader': 'change',
  'el-time-picker': 'change',
  'el-date-picker': 'change',
  'el-rate': 'change',
  'fc-amount': 'change',
  'fc-time-duration': 'change',
  'fc-date-duration': 'change',
  'fc-date-select': 'change',
  'fc-org-select': 'input',
  'fc-return-student': 'change',
  'fc-input-student': 'change',
  'fc-select-branch': 'change',
  'fc-filter-bank': 'change',
  'fc-select-school': 'change',
  'fc-select-bankList': 'change',
  'fc-select-employee': 'change',
  'fc-select-bank': 'change',
  'fc-uploadFile': 'change',
  'fc-total-money': 'change',
  'fc-upload-quantity': 'change',
  'fc-select-costType': 'change',
  'fc-select-finance': 'change',
  'fc-select-feeType': 'change',
  'fc-input-verify': 'change',
  'fc-per-list': 'change',
  'fc-source': 'change',
  'fc-api-select': 'change',
  'fc-vote': 'change'
}
